[package]
name = "nix_deploy"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = {version = "0.7.5", features = ["multipart", "http2"]}
tokio = {version = "1.37.0", features = ["full"]}
dotenv = "0.15.0"
